def main():
	adjective1 = raw_input("Please enter an adjective: ")
	adjective2 = raw_input("Please enter another adjective: ")
	bird = raw_input("Please enter a type of bird: ")
	room = raw_input("Please enter a room in a house: ")
	verbPast = raw_input("Please enter a past tense verb: ")
	verb = raw_input("Please enter a verb: ")
	name = raw_input("Please enter a name: ")
	noun1 = raw_input("Please enter a noun: ")
	liquid = raw_input("Please enter a liquid: ")
	verbing = raw_input("Please enter a verb that ends in ing: ")
	bodyPart = raw_input("Please enter a plural body part: ")
	pluNoun = raw_input("Please enter a plural noun: ")
	verbing2 = raw_input("Please enter another verb that ends in -ing: ")
	noun2 = raw_input("Please enter another noun: ")
	print("It was a " + adjective1 + ", cold November day. I woke up to the " + adjective2 + " smell of " + bird + " roasting in the " + room + " downstairs. I " + verbPast + " down the stairs to see if I could help " + verb + " the dinner. My mom said, 'See if " + name + " needs a fresh " + noun1 + ".' So i carried a tray of glasses full of " + liquid + " into the " + verbing + " room. When I got there, I couldn't believe my " + bodyPart + "! There were " + pluNoun + " " + verbing2 + " on the " + noun2 + "!")
	main()
main()

